# Generated by Django 6.0.2 on 2026-03-04 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Message'), django.core.validators.MaxValueValidator(5, 'Message')]),
        ),
    ]
