# Generated by Django 6.0.2 on 2026-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('USA', 'Estados Unidos'), ('CAN', 'Canadá'), ('MEX', 'México'), ('POR', 'Portugal'), ('ESP', 'Espanha'), ('FRA', 'França'), ('GER', 'Alemanha'), ('ITA', 'Itália'), ('GBR', 'Reino Unido'), ('JPN', 'Japão'), ('CHN', 'China'), ('RUS', 'Rússia'), ('IND', 'Índia'), ('AUS', 'Austrália'), ('ZAF', 'África do Sul'), ('EGY', 'Egito'), ('KOR', 'Coreia do Sul'), ('NGA', 'Nigéria'), ('COL', 'Colômbia'), ('CHI', 'Chile'), ('PER', 'Peru'), ('URU', 'Uruguai'), ('PAR', 'Paraguai'), ('BOL', 'Bolívia'), ('VEN', 'Venezuela'), ('ECU', 'Equador'), ('SWE', 'Suécia'), ('NOR', 'Noruega'), ('DEN', 'Dinamarca'), ('FIN', 'Finlândia'), ('NED', 'Países Baixos'), ('BEL', 'Bélgica'), ('SUI', 'Suíça'), ('AUT', 'Áustria'), ('POL', 'Polônia'), ('GRE', 'Grécia'), ('TUR', 'Turquia'), ('ISR', 'Israel'), ('SAU', 'Arábia Saudita'), ('UAE', 'Emirados Árabes Unidos'), ('THA', 'Tailândia'), ('VIE', 'Vietnã'), ('PHI', 'Filipinas'), ('NZL', 'Nova Zelândia')], max_length=100, null=True)),
            ],
        ),
    ]
